{% set name = "java-access-bridge-wrapper" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/java_access_bridge_wrapper-{{ version }}.tar.gz
  sha256: 77b9e88d84a74794fa69fda486dc756a8b4f69442d3f51551eb51935d8be70ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - java_tree_reader = 'JABWrapper.context_tree_reader:main'
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.6.2,<4.0.0
    - pywin32-on-windows
    - pywin32 >=300,<304
    - __win

test:
  imports:
    - JABWrapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/java-access-bridge-wrapper.git
  summary: Python wrapper for the Windows Java Access Bridge
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
